[colors.bright]
black = "0x181a1c"
blue = "0x72cce8"
cyan = "0x5eefc1"
green = "0x8dd274"
magenta = "0xba9cf3"
red = "0xff6578"
white = "0xe1e3e4"
yellow = "0xeacb64"

[colors.normal]
black = "0x181a1c"
blue = "0x72cce8"
cyan = "0x5eefc1"
green = "0x8dd274"
magenta = "0xba9cf3"
red = "0xff6578"
white = "0xe1e3e4"
yellow = "0xeacb64"

[colors.primary]
background = "0x2a2f38"
foreground = "0xe1e3e4"

[font]
size = 14

[font.bold]
family = "Caskaydia Cove Nerd Font"

[font.italic]
family = "Caskaydia Cove Nerd Font"

[font.normal]
family = "Caskaydia Cove Nerd Font"
style = "Regular"

[window]
opacity = 0.95

[window.padding]
x = 6
y = 6
