scan_timeout = 60
add_newline = false

[line_break]
disabled = false

[directory]
style = "bold blue"

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = ""
not_executable_symbol = ""
sigint_symbol = "ﭦ"
map_symbol = true

[git_branch]
format = "[$symbol$branch]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = " "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"
symbol = "🦀 "

[golang]
format = "[$symbol($version )]($style)"
symbol = " "

[lua]
format = "[$symbol($version )]($style)"
symbol = " "

[c]
format = "[$symbol($version )]($style)"
symbol = " "

[battery]
disabled = true

[localip]
ssh_only = false
format = '[$localipv4](bold cyan) '
disabled = false

[username]
style_user = 'green bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true

[sudo]
style = 'bold yellow'
format = '[$symbol]($style)'
symbol = '󰈸 '
disabled = false
