# Colors
[colors.primary]
background = "0x2a2f38"
foreground = "0xe1e3e4"

[colors.bright]
black = "0x16161e"
red = "0xf7768e"
green = "0x41a6b5"
yellow = "0xff9e64"
blue = "0x3d59a1"
magenta = "0x9d7cd8"
cyan = "0x7dcfff"
white = "0xc0caf5"

[colors.normal]
black = "0x414868"
red = "0xdb4b4b"
green = "0x73daca"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x458588"
white = "0x414868"

[font]
size = 14

[font.bold]
family = "Caskaydia Cove Nerd Font"

[font.italic]
family = "Caskaydia Cove Nerd Font"

[font.normal]
family = "Caskaydia Cove Nerd Font"
style = "Regular"

[window]
opacity = 1

[window.padding]
x = 6
y = 6
